### ISSUE TITLE
Unresolved dependency: org.walkmod#walkmod-findbugs-plugin

### ISSUE THREAD

**Issue by pkmusthafa** [walkmod/walkmod-core#78]
Hello,

Please help me to resolve the below issue : 

```
:: loading settings :: url = jar:file:/D:/Applns/walkmod-3.0.0/lib/ivy-2.4.0-rc1.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: resolving dependencies :: org.walkmod#walkmod-imports-cleaner-plugin-caller;working
        confs: [default]
        found org.walkmod#walkmod-imports-cleaner-plugin;2.0.3 in maven2
        [2.0.3] org.walkmod#walkmod-imports-cleaner-plugin;[2.0.0, 3.0.0)
        found org.walkmod#javalang;3.2.0 in maven2
        [3.2.0] org.walkmod#javalang;[3.0.0, 4.0.0)
        found org.walkmod#merger;1.0.1 in maven2
        [1.0.1] org.walkmod#merger;[1.0.1, 2.0)
        found org.walkmod#walkmod-sonar-plugin;1.2.2 in maven2
        [1.2.2] org.walkmod#walkmod-sonar-plugin;latest.integration
        found org.walkmod#javalang-compiler;2.3.7 in maven2
        [2.3.7] org.walkmod#javalang-compiler;[2.2, 3.0)
        found org.walkmod#javalang;4.8.7 in maven2
        [4.8.7] org.walkmod#javalang;[4.1.0, 5.0.0)
        found org.walkmod#model-checker;1.1 in maven2
        [1.1] org.walkmod#model-checker;[1.0, 2.0)
        found log4j#log4j;1.2.16 in maven2
        found org.walkmod#walkmod-refactor-plugin;2.3.3 in maven2
        [2.3.3] org.walkmod#walkmod-refactor-plugin;[2.3.3,3.0.0)
        found com.mashape.unirest#unirest-java;1.4.9 in maven2
        found org.apache.httpcomponents#httpclient;4.5.2 in maven2
        found org.apache.httpcomponents#httpcore;4.4.4 in maven2
        found commons-logging#commons-logging;1.2 in maven2
        found commons-codec#commons-codec;1.9 in maven2
        found org.apache.httpcomponents#httpasyncclient;4.1.1 in maven2
        found org.apache.httpcomponents#httpcore-nio;4.4.4 in maven2
        found org.apache.httpcomponents#httpmime;4.5.2 in maven2
        found org.json#json;20160212 in maven2
        found org.walkmod#walkmod-checkstyle-plugin;1.0.5 in maven2
        [1.0.5] org.walkmod#walkmod-checkstyle-plugin;latest.integration
        found org.walkmod#javalang;4.8.7 in maven2
        [4.8.7] org.walkmod#javalang;[4.5.0, 5.0)
        found org.walkmod#walkmod-dead-code-cleaner-plugin;1.3.3 in maven2
        [1.3.3] org.walkmod#walkmod-dead-code-cleaner-plugin;latest.integration
        found org.walkmod#walkmod-comments-cleaner-plugin;1.0.1 in maven2
        [1.0.1] org.walkmod#walkmod-comments-cleaner-plugin;latest.integration
        found org.walkmod#walkmod-javalang-plugin;3.0.5 in maven2
        [3.0.5] org.walkmod#walkmod-javalang-plugin;[2.0, 4.0)
        found org.walkmod#javalang;4.8.7 in maven2
        [4.8.7] org.walkmod#javalang;[3.1.0, 5.0.0)
        found com.squareup#javapoet;1.8.0 in maven2
        found org.walkmod#javalang-compiler;2.3.7 in maven2
        [2.3.7] org.walkmod#javalang-compiler;[2.0.0, 3.0.0)
:: resolution report :: resolve 12644ms :: artifacts dl 20ms
        :: evicted modules:
        org.walkmod#javalang;3.2.0 by [org.walkmod#javalang;4.8.7] in [default]
        org.walkmod#javalang-compiler;[2.0, 3.0) by [org.walkmod#javalang-compiler;2.3.7] in [default]
        org.apache.httpcomponents#httpclient;4.5.1 by [org.apache.httpcomponents#httpclient;4.5.2] in [default]
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   26  |   8   |   0   |   3   ||   34  |   0   |
        ---------------------------------------------------------------------

:: problems summary ::
:::: WARNINGS
                module not found: org.walkmod#walkmod-findbugs-plugin;latest.integration

        ==== maven2: tried

          http://repo1.maven.org/maven2/org/walkmod/walkmod-findbugs-plugin/[revision]/walkmod-findbugs-plugin-[revision].pom

          -- artifact org.walkmod#walkmod-findbugs-plugin;latest.integration!walkmod-findbugs-plugin.jar:

          http://repo1.maven.org/maven2/org/walkmod/walkmod-findbugs-plugin/[revision]/walkmod-findbugs-plugin-[revision].jar

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: org.walkmod#walkmod-findbugs-plugin;latest.integration: not found

                ::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
 WARN [main] - unresolved dependency: org.walkmod#walkmod-findbugs-plugin;latest.integration: not found
ERROR [main] - Invalid configuration
org.walkmod.conf.ConfigurationException: Ivy can not resolve the artifacts. Cause: unresolved dependency: org.walkmod#walkmod-findbugs-plugin;latest.integration: not found
        at org.walkmod.conf.providers.IvyConfigurationProvider.resolveArtifacts(IvyConfigurationProvider.java:233)
        at org.walkmod.conf.providers.IvyConfigurationProvider.load(IvyConfigurationProvider.java:156)
        at org.walkmod.conf.ConfigurationManager.executeConfigurationProviders(ConfigurationManager.java:124)
        at org.walkmod.conf.ConfigurationManager.addProviders(ConfigurationManager.java:61)
        at org.walkmod.conf.ConfigurationManager.<init>(ConfigurationManager.java:75)
        at org.walkmod.conf.ConfigurationManager.<init>(ConfigurationManager.java:79)
        at org.walkmod.WalkModFacade.readConfig(WalkModFacade.java:181)
        at org.walkmod.WalkModFacade.run(WalkModFacade.java:256)
        at org.walkmod.WalkModFacade.apply(WalkModFacade.java:142)
        at org.walkmod.commands.ApplyCommand.execute(ApplyCommand.java:42)
        at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:172)
        at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:197)
ERROR [main] - Invalid configuration
java.lang.NullPointerException
        at org.walkmod.WalkModFacade.run(WalkModFacade.java:264)
        at org.walkmod.WalkModFacade.apply(WalkModFacade.java:142)
        at org.walkmod.commands.ApplyCommand.execute(ApplyCommand.java:42)
        at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:172)
        at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:197)
Exception in thread "main" java.lang.NullPointerException
        at org.walkmod.WalkModFacade.run(WalkModFacade.java:284)
        at org.walkmod.WalkModFacade.apply(WalkModFacade.java:142)
        at org.walkmod.commands.ApplyCommand.execute(ApplyCommand.java:42)
        at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:172)
        at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:197)
```

**Comment by rpau** [comment]
Walkmod uses `Ivy` internally to resolve the plugins. Could you use the markdown language for the stacktrace? It becomes more readable.

Sometimes, Ivy become crazy when there are network issues. Could you remove your .$HOME/.ivy directory and try again?

**Comment by pkmusthafa** [comment]
Thank you,

1.  I have an additional question, Is there any option to avoid the default formatting while running walkmod? I need to retain the comments and code indent which is already there in my src file.
But need to run import-cleaner and dead-code-cleaner without affecting the existing format.  Please advise...

2.  I tried after removing the .ivy from home directory. But still it is showing the below error  for findbugs plugin.

 WARN [main] - unresolved dependency: org.walkmod#walkmod-findbugs-plugin;latest.integration: not found
ERROR [main] - Invalid configuration
org.walkmod.conf.ConfigurationException: Ivy can not resolve the artifacts. Cause: unresolved dependency: org.walkmod#walkmod-findbugs-plugin;latest.integration: not found
        at org.walkmod.conf.providers.IvyConfigurationProvider.resolveArtifacts(IvyConfigurationProvider.java:233)
        at org.walkmod.conf.providers.IvyConfigurationProvider.load(IvyConfigurationProvider.java:156)
        at org.walkmod.conf.ConfigurationManager.executeConfigurationProviders(ConfigurationManager.java:124)
        at org.walkmod.conf.ConfigurationManager.addProviders(ConfigurationManager.java:61)
        at org.walkmod.conf.ConfigurationManager.<init>(ConfigurationManager.java:75)
        at org.walkmod.conf.ConfigurationManager.<init>(ConfigurationManager.java:79)
        at org.walkmod.WalkModFacade.readConfig(WalkModFacade.java:181)
        at org.walkmod.WalkModFacade.run(WalkModFacade.java:256)
        at org.walkmod.WalkModFacade.apply(WalkModFacade.java:142)
        at org.walkmod.commands.ApplyCommand.execute(ApplyCommand.java:40)
        at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:172)
        at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:197)
ERROR [main] - Invalid configuration
java.lang.NullPointerException
        at org.walkmod.WalkModFacade.run(WalkModFacade.java:264)
        at org.walkmod.WalkModFacade.apply(WalkModFacade.java:142)
        at org.walkmod.commands.ApplyCommand.execute(ApplyCommand.java:40)
        at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:172)
        at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:197)
Exception in thread "main" java.lang.NullPointerException
        at org.walkmod.WalkModFacade.run(WalkModFacade.java:284)
        at org.walkmod.WalkModFacade.apply(WalkModFacade.java:142)
        at org.walkmod.commands.ApplyCommand.execute(ApplyCommand.java:40)
        at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:172)
        at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:197)

**Comment by pkmusthafa** [comment]
@rpau Thank  you for quick response.

I am not using any formatter file in my walkmod.xml

See the portion of the code which is formatted after walkmod apply..
src code: 

public static void main(String[] args) {
		
		FirstWalkMod firstWalkMod = new FirstWalkMod();
		String name = firstWalkMod.
				getName();
		firstWalkMod.
		sayHello(name);
		
		}

After walkmod apply :

public static void main(String[] args) {

    FirstWalkMod firstWalkMod = new FirstWalkMod();
    String name = firstWalkMod.getName();
    firstWalkMod.sayHello(name);

  }

Can I avoid this default formating ? 

My project requirement is 'do not change format of of existing code that will trigger merge issues , but need to use some specific plugins' such as import-cleaner, dead-code-cleaner etc.

So I am doing some excercise with this example

![walkmod](https://user-images.githubusercontent.com/34713602/35090081-ab67ed1a-fc5e-11e7-9e20-fc87399c665b.jpg)


Thank you for help.

**Comment by rpau** [comment]
Ok, this is what I was suspecting. Tips:

1. -**Remove the `plugins` tag**. It is no longer necessary: walkmod infer this from your configuration. Probably ivy is getting issues when you specify latest.integration. But, I am going to check.
2. The `onlyWriteChanges` param is redundant. This is its default value and thus, you do not need it.
3. When you use XML configuration files, in order to ensure retro-compatibility, the eclipse formatter is applied. **Configuration files are no longer recommended since people are usually focused on running pmd, checkstyle or findbugs**, and when you run walkmod as it is explained in the website, your current format is not changed. Most of the online documentation (slides from conferences) explains how to respect the formatting. What you need is to add inside the `chain` nodes, and after your transformations like this:

`https://github.com/rpau/test/blob/1dfa1108fa5692680aa233176871f8f5c2cb1d25/walkmod.xml`

**Comment by pkmusthafa** [comment]
Thank you,
Let me try this and will update you.

Regards,

**Comment by pkmusthafa** [comment]
@rpau ,

Successfully run the sonar transformations , But noted the following Errors:
while applying transformation <transformation type="sonar:AddSwitchDefaultCase"/>
getting the below error : 

INFO [main] - ** THE TRANSFORMATION CHAIN default STARTS **
--------------------------------------------------------------------------------
Error visiting a Java source file - org.walkmod.util.location.LocationImpl@35f51410
        at org.walkmod.javalang.walkers.DefaultJavaWalker.visit(DefaultJavaWalker.java:505)
        at org.walkmod.javalang.walkers.DefaultJavaWalker.visit(DefaultJavaWalker.java:250)
        at org.walkmod.javalang.walkers.DefaultJavaWalker.accept(DefaultJavaWalker.java:91)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.walkmod.walkers.AbstractWalker.walk(AbstractWalker.java:264)
        at org.walkmod.walkers.AbstractWalker.execute(AbstractWalker.java:279)
        at org.walkmod.javalang.walkers.DefaultJavaWalker.execute(DefaultJavaWalker.java:173)
        at org.walkmod.impl.DefaultChainWalkerInvocation.invoke(DefaultChainWalkerInvocation.java:41)
        at org.walkmod.impl.DefaultChainInvocation.invoke(DefaultChainInvocation.java:38)
        at org.walkmod.impl.DefaultChainAdapter.execute(DefaultChainAdapter.java:166)
        at org.walkmod.conf.entities.impl.ConfigurationImpl.executeChain(ConfigurationImpl.java:731)
        at org.walkmod.conf.entities.impl.ConfigurationImpl.execute(ConfigurationImpl.java:825)
        at org.walkmod.WalkModFacade.run(WalkModFacade.java:284)
        at org.walkmod.WalkModFacade.apply(WalkModFacade.java:142)
        at org.walkmod.commands.ApplyCommand.execute(ApplyCommand.java:42)
        at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:172)
        at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:197)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -2
        at java.lang.String.substring(String.java:1911)
        at org.walkmod.javalang.actions.FormatterHelper.indent(FormatterHelper.java:13)
        at org.walkmod.javalang.actions.AppendAction.getText(AppendAction.java:95)
        at org.walkmod.javalang.actions.AppendAction.<init>(AppendAction.java:60)
        at org.walkmod.javalang.walkers.ChangeLogVisitor.applyAppend(ChangeLogVisitor.java:379)
        at org.walkmod.javalang.walkers.ChangeLogVisitor.inferASTChanges(ChangeLogVisitor.java:493)
        at org.walkmod.javalang.walkers.ChangeLogVisitor.visit(ChangeLogVisitor.java:2450)
        at org.walkmod.javalang.walkers.ChangeLogVisitor.visit(ChangeLogVisitor.java:130)
        at org.walkmod.javalang.ast.stmt.SwitchStmt.accept(SwitchStmt.java:97)
        at org.walkmod.javalang.walkers.ChangeLogVisitor.inferASTChanges(ChangeLogVisitor.java:522)
        at org.walkmod.javalang.walkers.ChangeLogVisitor.visit(ChangeLogVisitor.java:2371)
        at org.walkmod.javalang.walkers.ChangeLogVisitor.visit(ChangeLogVisitor.java:130)
        at org.walkmod.javalang.ast.stmt.BlockStmt.accept(BlockStmt.java:87)
        at org.walkmod.javalang.walkers.ChangeLogVisitor.inferASTChanges(ChangeLogVisitor.java:580)
        at org.walkmod.javalang.walkers.ChangeLogVisitor.visit(ChangeLogVisitor.java:823)
        at org.walkmod.javalang.walkers.ChangeLogVisitor.visit(ChangeLogVisitor.java:130)
        at org.walkmod.javalang.ast.body.MethodDeclaration.accept(MethodDeclaration.java:205)
        at org.walkmod.javalang.walkers.ChangeLogVisitor.inferASTChanges(ChangeLogVisitor.java:522)
        at org.walkmod.javalang.walkers.ChangeLogVisitor.visit(ChangeLogVisitor.java:734)
        at org.walkmod.javalang.walkers.ChangeLogVisitor.visit(ChangeLogVisitor.java:130)
        at org.walkmod.javalang.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:136)
        at org.walkmod.javalang.walkers.ChangeLogVisitor.inferASTChanges(ChangeLogVisitor.java:522)
        at org.walkmod.javalang.walkers.ChangeLogVisitor.visit(ChangeLogVisitor.java:659)
        at org.walkmod.javalang.walkers.DefaultJavaWalker.analyzeChanges(DefaultJavaWalker.java:322)
        at org.walkmod.javalang.walkers.DefaultJavaWalker.write(DefaultJavaWalker.java:457)
        at org.walkmod.walkers.AbstractWalker.writeAll(AbstractWalker.java:185)
        at org.walkmod.walkers.AbstractWalker.visit(AbstractWalker.java:173)
        at org.walkmod.javalang.walkers.DefaultJavaWalker.visit(DefaultJavaWalker.java:497)
        ... 19 more
 INFO [main] - **No sources changed**

 INFO [main] - TRANSFORMATION CHAIN SUCCESS
--------------------------------------------------------------------------------
 INFO [main] - Total time: 0.78 seconds
 INFO [main] - Finished at: Fri, 19 Jan 2018 18:01:04
 INFO [main] - Final memory: 82 M/ 119 M
 INFO [main] - Total modified files: 0
--------------------------------------------------------

and the below is the code expected to change with default option

int number=20;  
		
	    switch(number){  
	    	case 10: System.out.println("10");
	    	break;  
	    	case 20: System.out.println("20");
	    	break;  
	    	case 30: System.out.println("30");
	    	break;  
	    }  

Also the transformations  <transformation type="sonar:ArrayDesignatorOnType"/> and <transformation type="sonar:RemoveEmptyMethod"/> are not working as expected.

The modifications are not wrting properly in the src file. 

Thanks and regards,

**Comment by rpau** [comment]
1.  The produced exception seems related with the writing process. Could you create a gist [here](https://gist.github.com/) in GitHub or upload your testing file to validate what is wrong (I need to validate indentation characters)

2. Regarding the transformations that you say that are not working as expected, could you show to me the some examples where it is not working? Otherwise, it is impossible understanding what needs to be fixed.

**Comment by pkmusthafa** [comment]
Hello,

I have uploaded the below details :

 FirstWalkMod_original.java => The src java file, 

 FirstWalkMod_transformed.java => The transformed java file without the transformations 'sonar:ArrayDesignatorOnType' and 'sonar:RemoveEmptyMethod'. 

FirstWalkMod_sonarArrayDesignatorOnType.java => The transformed java file after enabling 'sonar:ArrayDesignatorOnType'

FirstWalkMod_sonarRemoveEmptyMethod.java => The transformed java file after enabling 'sonar:RemoveEmptyMethod'.

 And the corresponding walkmod.xml

https://gist.github.com/pkmusthafa/c18fcb6b25435266bac4522e78b5116b

Thanks and Regards,

**Comment by rpau** [comment]
Thanks for the info.
There are wrong cases, and I will look at them today. I will keep you informed.

**Comment by rpau** [comment]
I have fixed two issues:

https://github.com/rpau/javalang/pull/30
https://github.com/walkmod/walkmod-sonar-plugin/pull/14

However, I am still experimenting issues because there are many simultaneous changes in the same file. So, after I release my changes to the Maven repo, you will be able to run all your transformations separately. However, I am trying to understand the issue related the sequence of changes before releasing.

**Comment by pkmusthafa** [comment]
Thank you.
Have a nice day!.

**Comment by rpau** [comment]
@pkmusthafa All your issues have been fixed in these PRs:

https://github.com/walkmod/walkmod-sonar-plugin/pull/15
https://github.com/walkmod/walkmod-javalang-plugin/pull/15

There are new releases pending to be published in Maven central. Tomorrow, if you run walkmod again in your project, walkmod will be upgraded automatically and you will see if everything has been fixed.

I close this issue, but feel free to reopen it if you have any comments or other issues.

**Comment by pkmusthafa** [comment]
Thank you.
