### ISSUE TITLE
org.xml.sax.SAXParseExceptionpublicId: -//WALKMOD//DTD; systemId: http://<ClientSite>/ProxyWarning.html; lineNumber: 1; columnNumber: 3; The markup declarations contained or pointed to by the document type declaration must be well-formed.

### ISSUE THREAD

**Issue by fazith24** [walkmod/walkmod-core#82]
Hi,
  I am facing the below error while integrating walkmod to my spring MVC application. I feel it might because of proxy since i am in VPN. all the proxy configuration is already configured in my settings.xml. Do I need to configure proxy somewhere else for walkmod or is a different issue?

INFO [main] - C:\Users\<User>\IdeaProjects\<project-folder>\walkmod.xml [ok]
FATAL [main] - The markup declarations contained or pointed to by the document type declaration must be well-formed. at (-//WALKMOD//DTD:1:3)
org.xml.sax.SAXParseExceptionpublicId: -//WALKMOD//DTD; systemId: http://<ClientSite>/ProxyWarning.html; lineNumber: 1; columnNumber: 3; The markup declarations contained or pointed to by the document type declaration must be well-formed.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
        at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.scanDecls(XMLDTDScannerImpl.java:2039)
        at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.scanDTDExternalSubset(XMLDTDScannerImpl.java:306)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1174)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1045)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:959)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
        at org.walkmod.util.DomHelper.parse(DomHelper.java:90)
        at org.walkmod.conf.providers.PluginsConfigurationProvider.lookUpDocument(PluginsConfigurationProvider.java:114)
        at org.walkmod.conf.providers.PluginsConfigurationProvider.init(PluginsConfigurationProvider.java:80)
        at org.walkmod.conf.ConfigurationManager.executeConfigurationProviders(ConfigurationManager.java:123)
        at org.walkmod.conf.ConfigurationManager.addProviders(ConfigurationManager.java:61)
        at org.walkmod.conf.ConfigurationManager.<init>(ConfigurationManager.java:75)
        at org.walkmod.conf.ConfigurationManager.<init>(ConfigurationManager.java:79)
        at org.walkmod.WalkModFacade.readConfig(WalkModFacade.java:181)
        at org.walkmod.WalkModFacade.run(WalkModFacade.java:256)
        at org.walkmod.WalkModFacade.check(WalkModFacade.java:303)
        at org.walkmod.commands.CheckCommand.execute(CheckCommand.java:40)
        at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:172)
        at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:197)
ERROR [main] - C:\Users\<user>\IdeaProjects\faz-sales-express\walkmod.xml is invalid. Please, execute walkmod with -e to see the details.
ERROR [main] - C:\Users\<user>\IdeaProjects\faz-sales-express\walkmod.xml is invalid. Please, execute walkmod with -e to see the details.
Exception in thread "main" java.lang.NullPointerException
        at org.walkmod.WalkModFacade.run(WalkModFacade.java:284)
        at org.walkmod.WalkModFacade.check(WalkModFacade.java:303)
        at org.walkmod.commands.CheckCommand.execute(CheckCommand.java:40)
        at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:172)
        at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:197)

![image](https://user-images.githubusercontent.com/38099087/38357305-cfe38a2e-38df-11e8-9e8e-e4b3d4385428.png)

**Comment by samLuchs1** [comment]
nuttellabox>
