### ISSUE TITLE
NPE on walkmod plugins

### ISSUE THREAD

**Issue by imranbutt-java** [walkmod/walkmod-core#85]
C:\UBS\Dev\Softwares\walkmod-3.0.0\config>
C:\UBS\Dev\Softwares\walkmod-3.0.0\config>walkmod --version
INFO [main] - Java version: 1.8.0_171
INFO [main] - Java Home: C:\Program Files\Java\jdk1.8.0_171\jre
INFO [main] - OS: Windows 7, Vesion: 6.1
                 _    _       _ _   ___  ___          _
                | |  | |     | | |  |  \/  |         | |
                | |  | | __ _| | | _| .  . | ___   __| |
                | |/\| |/ _` | | |/ / |\/| |/ _ \ / _` |
                \  /\  / (_| | |   <| |  | | (_) | (_| |
                 \/  \/ \__,_|_|_|\_\_|  |_/\___/ \__,_|
An open source tool to apply code conventions
version 3.0 - February 2017 -
Walkmod version "3.0"
Java version: 1.8.0_171
Java Home: C:\Program Files\Java\jdk1.8.0_171\jre
OS: Windows 7, Version: 6.1
C:\UBS\Dev\Softwares\walkmod-3.0.0\config>walkmod plugins
INFO [main] - Java version: 1.8.0_171
INFO [main] - Java Home: C:\Program Files\Java\jdk1.8.0_171\jre
INFO [main] - OS: Windows 7, Vesion: 6.1
                 _    _       _ _   ___  ___          _
                | |  | |     | | |  |  \/  |         | |
                | |  | | __ _| | | _| .  . | ___   __| |
                | |/\| |/ _` | | |/ / |\/| |/ _ \ / _` |
                \  /\  / (_| | |   <| |  | | (_) | (_| |
                 \/  \/ \__,_|_|_|\_\_|  |_/\___/ \__,_|
An open source tool to apply code conventions
version 3.0 - February 2017 -
Exception in thread "main" Invalid plugins URL - org.walkmod.util.location.LocationImpl@6b57696f
at org.walkmod.commands.PrintPluginsCommand.execute(PrintPluginsCommand.java:172)
at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:172)
at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:197)
Caused by: java.lang.NullPointerException
... 3 more
C:\UBS\Dev\Softwares\walkmod-3.0.0\config>

**Comment by imranbutt-java** [comment]
I have downloaded walkmod and set its path. On running _**walkmod --version**_ it shows version properly but on running _**walkmod plugins**_ it gives NPE. Please, guide, if I am missing anything.
